import type { FormValue } from "../form/types";
import { safeGet, safeSet } from "./local-storage";

const PRESETS_KEY = "darkroomscad:presets:v1";

export interface Preset {
  id: string;
  name: string;
  values: Record<string, FormValue>;
}

function isPreset(p: unknown): p is Preset {
  if (!p || typeof p !== "object") return false;
  const o = p as Record<string, unknown>;
  return typeof o.id === "string"
    && typeof o.name === "string"
    && !!o.values && typeof o.values === "object" && !Array.isArray(o.values);
}

export function parsePresets(raw: string | null): Preset[] {
  if (!raw) return [];
  let arr: unknown;
  try {
    arr = JSON.parse(raw);
  } catch {
    return [];
  }
  return Array.isArray(arr) ? arr.filter(isPreset) : [];
}

// Add a new preset, or overwrite the existing one with the same name
// (case-insensitive, trimmed). Pure — the caller supplies the id.
export function upsertPreset(
  list: Preset[],
  name: string,
  values: Record<string, FormValue>,
  id: string,
): Preset[] {
  const trimmed = name.trim();
  const existing = list.find((p) => p.name.toLowerCase() === trimmed.toLowerCase());
  if (existing) return list.map((p) => (p.id === existing.id ? { ...p, values } : p));
  return [...list, { id, name: trimmed, values }];
}

export function deletePreset(list: Preset[], id: string): Preset[] {
  return list.filter((p) => p.id !== id);
}

function isFormValue(v: unknown): v is FormValue {
  return typeof v === "string" || typeof v === "number" || typeof v === "boolean";
}

// Imported files are foreign input: keep only primitive values (mirrors
// isFormValue in config-store.ts) so a crafted file can't smuggle objects
// into form state.
export function sanitizePresetValues(values: Record<string, unknown>): Record<string, FormValue> {
  const out: Record<string, FormValue> = {};
  for (const [k, v] of Object.entries(values)) {
    if (isFormValue(v)) out[k] = v;
  }
  return out;
}

// Merge imported presets into an existing list by name (case-insensitive,
// same rule as upsertPreset); imported ids are regenerated by the caller to
// avoid collisions. Returns the merged list and how many were added vs updated.
export function mergePresets(
  existing: Preset[],
  incoming: Preset[],
  newId: () => string,
): { list: Preset[]; added: number; updated: number } {
  let list = existing;
  let added = 0;
  let updated = 0;
  for (const p of incoming) {
    const trimmed = p.name.trim();
    const existed = list.some((e) => e.name.toLowerCase() === trimmed.toLowerCase());
    list = upsertPreset(list, p.name, p.values, newId());
    if (existed) updated++; else added++;
  }
  return { list, added, updated };
}

export function loadPresets(): Preset[] {
  return parsePresets(safeGet(PRESETS_KEY));
}

export function savePresets(list: Preset[]): void {
  safeSet(PRESETS_KEY, JSON.stringify(list));
}
