// Carrier value -> committed outline SVG url (generated by scripts/gen-carrier-outlines.ts).
export const CARRIER_OUTLINES: Record<string, string> = {
  "omega-d": "/outlines/omega-d.svg",
  "lpl-saunders-45xx": "/outlines/lpl-saunders-45xx.svg",
  "beseler-23c": "/outlines/beseler-23c.svg",
  "beseler-45": "/outlines/beseler-45.svg",
  "frameAndPegTest": "/outlines/frameAndPegTest.svg",
};
